# -*- coding: utf-8 -*-
"""中文路径 → 纯英文路径（目录与文件名均英文，去无意义编号，保留语义数字）。
由 scripts 维护；值即磁盘上的真实路径。"""

# 中文/特殊目录段 → 英文（用于路径翻译与侧边栏中文标签反查）
DIR_EN = {'360面经': 'qihoo', 'B站面经': 'bilibili', 'C++': 'cpp', 'CVTE面经': 'cvte', 'Shopee面经': 'shopee', 'c_base': 'c-basics', 'cpp_base': 'cpp-basics', 'golang_codes': 'codes', 'golang_files': 'files', 'micro_service': 'micro-service', 'moment面经': 'momenta', '中望面经': 'zwsoft', '二分查找': 'binary-search', '二叉树': 'binary-tree', '位运算': 'bit-manipulation', '其他游戏公司面经': 'game-companies', '其它': 'misc', '动态规划': 'dynamic-programming', '华为od算法大全': 'huawei-od', '华为面经': 'huawei', '双指针': 'two-pointers', '同程面经': 'tongcheng', '哈希表': 'hash-table', '喜马拉雅面经': 'ximalaya', '回溯': 'backtracking', '图': 'graph', '地平线面经': 'horizon', '声网': 'agora', '多益网络面经': 'duoyi', '大疆面经': 'dji', '奇安信面经': 'qianxin', '好未来面经': 'tal', '字典树': 'trie', '字节面经': 'bytedance', '富途面经': 'futu', '小米面经': 'xiaomi', '小红书面经': 'xiaohongshu', '小鹏汽车面经': 'xpeng', '影石面经': 'insta360', '得物面经': 'dewu', '微博面经': 'weibo', '快手面经': 'kuaishou', '拼多多面经': 'pinduoduo', '数组、字符串': 'array-string', '未岚大陆面经': 'weilanda', '栈': 'stack', '海康面经': 'hikvision', '淘米科技面经': 'taomee', '深信服面经': 'sangfor', '滑动窗口': 'sliding-window', '滴滴面经': 'didi', '牛客Top101-ACM模式': 'nowcoder-top101', '理想汽车面经': 'lixiang', '百度面经': 'baidu', '矩阵': 'matrix', '科大讯飞面经': 'iflytek', '米哈游面经': 'mihoyo', '网易面经': 'netease', '美团面经': 'meituan', '腾讯面经': 'tencent', '虎牙面经': 'huya', '诺瓦科技': 'nova', '迅雷面经': 'xunlei', '金山面经': 'kingsoft', '链表': 'linked-list', '阿里面经': 'alibaba', '零跑汽车面经': 'leapmotor', '面试经典100题': 'interview-100', '饿了么面经': 'eleme', 'MySQL': 'mysql', 'Redis': 'redis'}

# 中文完整路径(含 .md) → 英文完整路径（无 .md，目录+文件名均英文）
SLUGS = {
    'algorithm/华为od算法大全/报数游戏.md': 'algorithm/huawei-od/count-off-game',
    'algorithm/华为od算法大全/报文响应时间.md': 'algorithm/huawei-od/message-response-time',
    'algorithm/华为od算法大全/猜字谜.md': 'algorithm/huawei-od/word-puzzle',
    'algorithm/华为od算法大全/篮球游戏.md': 'algorithm/huawei-od/basketball-game',
    'algorithm/华为od算法大全/补种未成活胡杨.md': 'algorithm/huawei-od/replant-poplar',
    'algorithm/牛客Top101-ACM模式/二分查找排序.md': 'algorithm/nowcoder-top101/binary-search-sort',
    'algorithm/牛客Top101-ACM模式/二叉树.md': 'algorithm/nowcoder-top101/binary-tree',
    'algorithm/牛客Top101-ACM模式/动态规划.md': 'algorithm/nowcoder-top101/dynamic-programming',
    'algorithm/牛客Top101-ACM模式/双指针.md': 'algorithm/nowcoder-top101/two-pointers',
    'algorithm/牛客Top101-ACM模式/哈希.md': 'algorithm/nowcoder-top101/hash',
    'algorithm/牛客Top101-ACM模式/堆栈队列.md': 'algorithm/nowcoder-top101/stack-queue',
    'algorithm/牛客Top101-ACM模式/字符串.md': 'algorithm/nowcoder-top101/string',
    'algorithm/牛客Top101-ACM模式/贪心.md': 'algorithm/nowcoder-top101/greedy',
    'algorithm/牛客Top101-ACM模式/递归回溯.md': 'algorithm/nowcoder-top101/recursion-backtracking',
    'algorithm/牛客Top101-ACM模式/链表.md': 'algorithm/nowcoder-top101/linked-list',
    'algorithm/面试经典100题/二分查找/面试经典算法题53-搜索插入位置.md': 'algorithm/interview-100/binary-search/search-insert-position',
    'algorithm/面试经典100题/二分查找/面试经典算法题54-搜索二维矩阵.md': 'algorithm/interview-100/binary-search/search-2d-matrix',
    'algorithm/面试经典100题/二分查找/面试经典算法题55-寻找峰值.md': 'algorithm/interview-100/binary-search/find-peak-element',
    'algorithm/面试经典100题/二分查找/面试经典算法题56-搜索旋转排序数组.md': 'algorithm/interview-100/binary-search/search-rotated-array',
    'algorithm/面试经典100题/二分查找/面试经典算法题57-在排序数组中查找元素的第一个和最后一个位置.md': 'algorithm/interview-100/binary-search/first-last-position',
    'algorithm/面试经典100题/二分查找/面试经典算法题58-寻找两个正序数组的中位数.md': 'algorithm/interview-100/binary-search/median-two-arrays',
    'algorithm/面试经典100题/二分查找/面试经典算法题59-寻找旋转排序数组中的最小值.md': 'algorithm/interview-100/binary-search/min-rotated-array',
    'algorithm/面试经典100题/二叉树/面试经典算法题16-从前序与中序遍历序列构造二叉树.md': 'algorithm/interview-100/binary-tree/construct-binary-tree',
    'algorithm/面试经典100题/二叉树/面试经典算法题17 - 对称二叉树.md': 'algorithm/interview-100/binary-tree/symmetric-tree',
    'algorithm/面试经典100题/二叉树/面试经典算法题18-二叉树的层序遍历.md': 'algorithm/interview-100/binary-tree/level-order-traversal',
    'algorithm/面试经典100题/二叉树/面试经典算法题19-二叉树的后序遍历.md': 'algorithm/interview-100/binary-tree/postorder-traversal',
    'algorithm/面试经典100题/二叉树/面试经典算法题20-二叉树的前序遍历.md': 'algorithm/interview-100/binary-tree/preorder-traversal',
    'algorithm/面试经典100题/二叉树/面试经典算法题21-二叉树的右视图.md': 'algorithm/interview-100/binary-tree/right-side-view',
    'algorithm/面试经典100题/二叉树/面试经典算法题22-二叉树的中序遍历.md': 'algorithm/interview-100/binary-tree/inorder-traversal',
    'algorithm/面试经典100题/二叉树/面试经典算法题23-二叉树的最大深度.md': 'algorithm/interview-100/binary-tree/max-depth',
    'algorithm/面试经典100题/二叉树/面试经典算法题24-二叉树求根节点到叶子结点数字之和.md': 'algorithm/interview-100/binary-tree/sum-root-to-leaf',
    'algorithm/面试经典100题/二叉树/面试经典算法题25-二叉树展开为链表.md': 'algorithm/interview-100/binary-tree/flatten-binary-tree',
    'algorithm/面试经典100题/二叉树/面试经典算法题26-二叉搜索树的最近公共祖先.md': 'algorithm/interview-100/binary-tree/lowest-common-ancestor',
    'algorithm/面试经典100题/二叉树/面试经典算法题27-二叉搜索树中的众数.md': 'algorithm/interview-100/binary-tree/mode-bst',
    'algorithm/面试经典100题/二叉树/面试经典算法题28-翻转二叉树.md': 'algorithm/interview-100/binary-tree/invert-tree',
    'algorithm/面试经典100题/二叉树/面试经典算法题29-合并二叉树.md': 'algorithm/interview-100/binary-tree/merge-trees',
    'algorithm/面试经典100题/二叉树/面试经典算法题30-路径总和.md': 'algorithm/interview-100/binary-tree/path-sum',
    'algorithm/面试经典100题/二叉树/面试经典算法题31-完全二叉树的节点个数.md': 'algorithm/interview-100/binary-tree/count-complete-tree-nodes',
    'algorithm/面试经典100题/二叉树/面试经典算法题32-验证二叉树.md': 'algorithm/interview-100/binary-tree/validate-bst',
    'algorithm/面试经典100题/位运算/面试经典算法题60-二进制求和.md': 'algorithm/interview-100/bit-manipulation/add-binary',
    'algorithm/面试经典100题/位运算/面试经典算法题61-颠倒二进制位.md': 'algorithm/interview-100/bit-manipulation/reverse-bits',
    'algorithm/面试经典100题/位运算/面试经典算法题62-位1的个数.md': 'algorithm/interview-100/bit-manipulation/number-of-1-bits',
    'algorithm/面试经典100题/位运算/面试经典算法题63-只出现一次的数字.md': 'algorithm/interview-100/bit-manipulation/single-number',
    'algorithm/面试经典100题/位运算/面试经典算法题64-只出现一次的数字 II.md': 'algorithm/interview-100/bit-manipulation/single-number-2',
    'algorithm/面试经典100题/动态规划/恰好移动 k 步到达某一位置的方法数目.md': 'algorithm/interview-100/dynamic-programming/k-steps-ways',
    'algorithm/面试经典100题/动态规划/面试经典算法题73-爬楼梯.md': 'algorithm/interview-100/dynamic-programming/climbing-stairs',
    'algorithm/面试经典100题/动态规划/面试经典算法题74-打家劫舍.md': 'algorithm/interview-100/dynamic-programming/house-robber',
    'algorithm/面试经典100题/动态规划/面试经典算法题75-单词拆分.md': 'algorithm/interview-100/dynamic-programming/word-break',
    'algorithm/面试经典100题/动态规划/面试经典算法题76-零钱兑换.md': 'algorithm/interview-100/dynamic-programming/coin-change',
    'algorithm/面试经典100题/动态规划/面试经典算法题77-最长递增子序列.md': 'algorithm/interview-100/dynamic-programming/longest-increasing-subseq',
    'algorithm/面试经典100题/动态规划/面试经典算法题78-三角形最小路径和.md': 'algorithm/interview-100/dynamic-programming/triangle-min-path',
    'algorithm/面试经典100题/动态规划/面试经典算法题79-最小路径和.md': 'algorithm/interview-100/dynamic-programming/min-path-sum',
    'algorithm/面试经典100题/动态规划/面试经典算法题80-不同路径 II.md': 'algorithm/interview-100/dynamic-programming/unique-paths-2',
    'algorithm/面试经典100题/动态规划/面试经典算法题81-最长回文子串.md': 'algorithm/interview-100/dynamic-programming/longest-palindrome',
    'algorithm/面试经典100题/动态规划/面试经典算法题82-编辑距离.md': 'algorithm/interview-100/dynamic-programming/edit-distance',
    'algorithm/面试经典100题/动态规划/面试经典算法题83-买卖股票的最佳时机 III.md': 'algorithm/interview-100/dynamic-programming/best-stock-3',
    'algorithm/面试经典100题/动态规划/面试经典算法题84-买卖股票的最佳时机 IV.md': 'algorithm/interview-100/dynamic-programming/best-stock-4',
    'algorithm/面试经典100题/动态规划/面试经典算法题85-最大正方形.md': 'algorithm/interview-100/dynamic-programming/max-square',
    'algorithm/面试经典100题/双指针/面试经典算法1-合并两个有序数组.md': 'algorithm/interview-100/two-pointers/merge-sorted-arrays',
    'algorithm/面试经典100题/双指针/面试经典算法2-最长无重复子串.md': 'algorithm/interview-100/two-pointers/longest-substring',
    'algorithm/面试经典100题/双指针/面试经典算法3-判断子序列.md': 'algorithm/interview-100/two-pointers/is-subsequence',
    'algorithm/面试经典100题/双指针/面试经典算法4-删除有序数组中的重复项.md': 'algorithm/interview-100/two-pointers/remove-duplicates',
    'algorithm/面试经典100题/双指针/面试经典算法5-盛最多水的容器.md': 'algorithm/interview-100/two-pointers/container-most-water',
    'algorithm/面试经典100题/双指针/面试经典算法6-三数之和.md': 'algorithm/interview-100/two-pointers/3sum',
    'algorithm/面试经典100题/哈希表/面试经典算法题65-赎金信.md': 'algorithm/interview-100/hash-table/ransom-note',
    'algorithm/面试经典100题/哈希表/面试经典算法题66-同构字符串.md': 'algorithm/interview-100/hash-table/isomorphic-strings',
    'algorithm/面试经典100题/哈希表/面试经典算法题67-单词规律.md': 'algorithm/interview-100/hash-table/word-pattern',
    'algorithm/面试经典100题/哈希表/面试经典算法题68-有效的字母异位词.md': 'algorithm/interview-100/hash-table/valid-anagram',
    'algorithm/面试经典100题/哈希表/面试经典算法题69-两数之和.md': 'algorithm/interview-100/hash-table/two-sum',
    'algorithm/面试经典100题/哈希表/面试经典算法题70-快乐数.md': 'algorithm/interview-100/hash-table/happy-number',
    'algorithm/面试经典100题/哈希表/面试经典算法题71-存在重复元素 II.md': 'algorithm/interview-100/hash-table/contains-duplicate-2',
    'algorithm/面试经典100题/哈希表/面试经典算法题72-最长连续序列.md': 'algorithm/interview-100/hash-table/longest-consecutive',
    'algorithm/面试经典100题/回溯/面试经典算法题91-电话号码的字母组合.md': 'algorithm/interview-100/backtracking/letter-combinations',
    'algorithm/面试经典100题/回溯/面试经典算法题92-组合.md': 'algorithm/interview-100/backtracking/combinations',
    'algorithm/面试经典100题/回溯/面试经典算法题93-全排列.md': 'algorithm/interview-100/backtracking/permutations',
    'algorithm/面试经典100题/回溯/面试经典算法题94-组合总和.md': 'algorithm/interview-100/backtracking/combination-sum',
    'algorithm/面试经典100题/回溯/面试经典算法题95-N 皇后 II.md': 'algorithm/interview-100/backtracking/n-queens-2',
    'algorithm/面试经典100题/回溯/面试经典算法题96-括号生成.md': 'algorithm/interview-100/backtracking/generate-parentheses',
    'algorithm/面试经典100题/回溯/面试经典算法题97-单词搜索.md': 'algorithm/interview-100/backtracking/word-search',
    'algorithm/面试经典100题/图/面试经典算法题98-岛屿数量.md': 'algorithm/interview-100/graph/number-of-islands',
    'algorithm/面试经典100题/字典树/面试经典算法题100-单词搜索 II.md': 'algorithm/interview-100/trie/word-search-2',
    'algorithm/面试经典100题/字典树/面试经典算法题99-实现Tire（前缀树）.md': 'algorithm/interview-100/trie/implement-trie',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题33-最长公共前缀.md': 'algorithm/interview-100/array-string/longest-common-prefix',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题34-多数元素.md': 'algorithm/interview-100/array-string/majority-element',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题35-移除元素.md': 'algorithm/interview-100/array-string/remove-element',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题36-买卖股票的最佳时机.md': 'algorithm/interview-100/array-string/best-time-stock',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题37-反转字符串中的单词.md': 'algorithm/interview-100/array-string/reverse-words',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题38-轮转数组.md': 'algorithm/interview-100/array-string/rotate-array',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题39-买卖股票的最佳时机2.md': 'algorithm/interview-100/array-string/best-time-stock-2',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题40-跳跃游戏.md': 'algorithm/interview-100/array-string/jump-game',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题41-跳跃游戏2.md': 'algorithm/interview-100/array-string/jump-game-2',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题42-加油站.md': 'algorithm/interview-100/array-string/gas-station',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题43-Z字形变换.md': 'algorithm/interview-100/array-string/zigzag-conversion',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题44-接雨水.md': 'algorithm/interview-100/array-string/trapping-rain-water',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题45-分发糖果.md': 'algorithm/interview-100/array-string/candy',
    'algorithm/面试经典100题/数组、字符串/面试经典算法题46-找出字符串中第一个匹配项的下标.md': 'algorithm/interview-100/array-string/first-match-index',
    'algorithm/面试经典100题/栈/面试经典算法题50-有效的括号.md': 'algorithm/interview-100/stack/valid-parentheses',
    'algorithm/面试经典100题/栈/面试经典算法题51-最小栈.md': 'algorithm/interview-100/stack/min-stack',
    'algorithm/面试经典100题/栈/面试经典算法题52-逆波兰表达式求值.md': 'algorithm/interview-100/stack/eval-rpn',
    'algorithm/面试经典100题/滑动窗口/面试经典算法题47-长度最小的子数组.md': 'algorithm/interview-100/sliding-window/min-size-subarray',
    'algorithm/面试经典100题/滑动窗口/面试经典算法题48-串联所有单词的子串.md': 'algorithm/interview-100/sliding-window/substring-concat-words',
    'algorithm/面试经典100题/滑动窗口/面试经典算法题49-最小覆盖子串.md': 'algorithm/interview-100/sliding-window/min-window-substring',
    'algorithm/面试经典100题/矩阵/面试经典算法题86-有效的数独.md': 'algorithm/interview-100/matrix/valid-sudoku',
    'algorithm/面试经典100题/矩阵/面试经典算法题87-螺旋矩阵.md': 'algorithm/interview-100/matrix/spiral-matrix',
    'algorithm/面试经典100题/矩阵/面试经典算法题88-旋转图像.md': 'algorithm/interview-100/matrix/rotate-image',
    'algorithm/面试经典100题/矩阵/面试经典算法题89-矩阵置零.md': 'algorithm/interview-100/matrix/set-matrix-zeroes',
    'algorithm/面试经典100题/矩阵/面试经典算法题90-生命游戏.md': 'algorithm/interview-100/matrix/game-of-life',
    'algorithm/面试经典100题/链表/面试经典算法10-K个一组反转链表.md': 'algorithm/interview-100/linked-list/reverse-k-group',
    'algorithm/面试经典100题/链表/面试经典算法11-删除链表的节点.md': 'algorithm/interview-100/linked-list/delete-node',
    'algorithm/面试经典100题/链表/面试经典算法12-重排链表.md': 'algorithm/interview-100/linked-list/reorder-list',
    'algorithm/面试经典100题/链表/面试经典算法13-删除链表的倒数第N个结点.md': 'algorithm/interview-100/linked-list/remove-nth-from-end',
    'algorithm/面试经典100题/链表/面试经典算法14-旋转链表.md': 'algorithm/interview-100/linked-list/rotate-list',
    'algorithm/面试经典100题/链表/面试经典算法15-LRU缓存.md': 'algorithm/interview-100/linked-list/lru-cache',
    'algorithm/面试经典100题/链表/面试经典算法7-反转链表.md': 'algorithm/interview-100/linked-list/reverse-linked-list',
    'algorithm/面试经典100题/链表/面试经典算法8-环形链表.md': 'algorithm/interview-100/linked-list/linked-list-cycle',
    'algorithm/面试经典100题/链表/面试经典算法9-反转链表Ⅱ.md': 'algorithm/interview-100/linked-list/reverse-linked-list-2',
    'cpp/C++学习要点小结.md': 'cpp/cpp-learning-notes',
    'cpp/c_base/C语言基础数据结构与算法总结.md': 'cpp/c-basics/c-data-structures-algorithms',
    'cpp/c_base/C语言引用详解.md': 'cpp/c-basics/c-reference-guide',
    'cpp/c_base/C语言指针详解.md': 'cpp/c-basics/c-pointer-guide',
    'cpp/c_base/C语言高频面试题-1.md': 'cpp/c-basics/c-interview-questions-1',
    'cpp/c_base/C语言高频面试题-2.md': 'cpp/c-basics/c-interview-questions-2',
    'cpp/cpp_base/C++ 基础面试问题及详细解答.md': 'cpp/cpp-basics/cpp-basics-faq',
    'cpp/cpp_base/C++11新标准.md': 'cpp/cpp-basics/cpp11',
    'cpp/cpp_base/C++14新标准.md': 'cpp/cpp-basics/cpp14',
    'cpp/cpp_base/C++17新特性.md': 'cpp/cpp-basics/cpp17-features',
    'cpp/cpp_base/C++STL剖析.md': 'cpp/cpp-basics/cpp-stl-analysis',
    'cpp/cpp_base/C++中const关键字的作用.md': 'cpp/cpp-basics/cpp-const',
    'cpp/cpp_base/C++中new和malloc的区别？.md': 'cpp/cpp-basics/cpp-new-vs-malloc',
    'cpp/cpp_base/C++中指针和引用的区别？.md': 'cpp/cpp-basics/cpp-pointer-vs-reference',
    'cpp/cpp_base/C++中数组和链表的区别？.md': 'cpp/cpp-basics/cpp-array-vs-list',
    'cpp/cpp_base/C++中的四种cast详解.md': 'cpp/cpp-basics/cpp-four-casts',
    'cpp/cpp_base/C++中的左值和右值以及一些延伸问题小结.md': 'cpp/cpp-basics/cpp-lvalue-rvalue',
    'cpp/cpp_base/C++中重载、重写、同名隐藏的用法及区别？.md': 'cpp/cpp-basics/cpp-overload-override-hide',
    'cpp/cpp_base/C++内存管理深度.md': 'cpp/cpp-basics/cpp-memory-management',
    'cpp/cpp_base/C++可调用对象.md': 'cpp/cpp-basics/cpp-callable-objects',
    'cpp/cpp_base/C++基础面试题.md': 'cpp/cpp-basics/cpp-basic-questions',
    'cpp/cpp_base/C++多线程.md': 'cpp/cpp-basics/cpp-multithreading',
    'cpp/cpp_base/C++多线程线程安全是怎么保证的.md': 'cpp/cpp-basics/cpp-thread-safety',
    'cpp/cpp_base/C++多线程编程.md': 'cpp/cpp-basics/cpp-multithreading-programming',
    'cpp/cpp_base/C++智能指针.md': 'cpp/cpp-basics/cpp-smart-pointers',
    'cpp/cpp_base/C++智能指针全解析：从auto_ptr到weak_ptr，彻底掌握内存管理利器.md': 'cpp/cpp-basics/cpp-smart-pointers-deep',
    'cpp/cpp_base/C++的编译过程？.md': 'cpp/cpp-basics/cpp-compilation-process',
    'cpp/cpp_base/C++虚函数.md': 'cpp/cpp-basics/cpp-virtual-functions',
    'cpp/cpp_base/C++设计模式.md': 'cpp/cpp-basics/cpp-design-patterns',
    'cpp/cpp_base/C++面试连环问-STL篇.md': 'cpp/cpp-basics/cpp-interview-stl',
    'cpp/cpp_base/C++面试连环问-内存管理篇.md': 'cpp/cpp-basics/cpp-interview-memory',
    'cpp/cpp_base/C++面试连环问-基础篇.md': 'cpp/cpp-basics/cpp-interview-basics',
    'cpp/cpp_base/C++面试连环问-面向对象篇.md': 'cpp/cpp-basics/cpp-interview-oop',
    'cpp/cpp_base/C_C++后端开发面试问题与拓展.md': 'cpp/cpp-basics/c-cpp-backend-questions',
    'cpp/cpp_base/TCMalloc深度解析：Google高性能内存分配器的秘密武器.md': 'cpp/cpp-basics/tcmalloc-deep-dive',
    'cpp/cpp_base/一文学透C++中static的用法.md': 'cpp/cpp-basics/cpp-static',
    'cpp/cpp_base/值传递、指针传递、引用传递的区别.md': 'cpp/cpp-basics/pass-by-value-vs-reference',
    'cpp/cpp_base/哈希冲突怎么解决？你学会了吗？.md': 'cpp/cpp-basics/hash-collision-solutions',
    'cpp/cpp_base/彻底拿捏stdvector.md': 'cpp/cpp-basics/std-vector-guide',
    'cpp/cpp_base/春招C++面经汇总--上.md': 'cpp/cpp-basics/spring-interview-cpp-1',
    'cpp/cpp_base/深入剖析C++ shared_ptr 的线程安全性：从源码到实践.md': 'cpp/cpp-basics/cpp-shared-ptr-thread-safety',
    'cpp/cpp_base/牛客网C++社招开发高频算法题目整理.md': 'cpp/cpp-basics/nowcoder-cpp-algorithms',
    'cpp/cpp_base/重学C++.md': 'cpp/cpp-basics/relearn-cpp',
    'data-structure/二叉树精讲.md': 'data-structure/binary-tree-guide',
    'data-structure/十大排序.md': 'data-structure/ten-sorting-algorithms',
    'data-structure/常见的查找算法总结.md': 'data-structure/search-algorithms-summary',
    'data-structure/校招生必知必会的几种经典算法.md': 'data-structure/classic-algorithms-new-grads',
    'data-structure/经典算法-分支限界法.md': 'data-structure/branch-and-bound',
    'data-structure/经典算法-分治算法.md': 'data-structure/divide-and-conquer',
    'data-structure/经典算法-动态规划.md': 'data-structure/dynamic-programming',
    'data-structure/经典算法-回溯算法.md': 'data-structure/backtracking',
    'data-structure/经典算法-贪心算法.md': 'data-structure/greedy-algorithm',
    'git/Git基本命令.md': 'git/git-basic-commands',
    'git/Git基本命令详解.md': 'git/git-commands-guide',
    'git/Git实战.md': 'git/git-in-action',
    'golang/golang_codes/micro_service/FINAL_TEST_REPORT.md': 'golang/codes/micro-service/final-test-report',
    'golang/golang_codes/micro_service/PROJECT_TEST_REPORT.md': 'golang/codes/micro-service/project-test-report',
    'golang/golang_codes/micro_service/README.md': 'golang/codes/micro-service/readme',
    'golang/golang_codes/micro_service/docs/API.md': 'golang/codes/micro-service/docs/api',
    'golang/golang_files/base/GC机制.md': 'golang/files/base/gc-mechanism',
    'golang/golang_files/base/GMP模型.md': 'golang/files/base/gmp-model',
    'golang/golang_files/base/Gin框架.md': 'golang/files/base/gin-framework',
    'golang/golang_files/base/Golang入门.md': 'golang/files/base/golang-intro',
    'golang/golang_files/base/Golang即时通信系统.md': 'golang/files/base/golang-chat-system',
    'interview/C++/360面经/360C++一面面经.md': 'interview/cpp/qihoo/360-cpp-round-1',
    'interview/C++/360面经/360C++二面面经.md': 'interview/cpp/qihoo/360-cpp-round-2',
    'interview/C++/360面经/360嵌入式一面.md': 'interview/cpp/qihoo/360-embedded-round-1',
    'interview/C++/B站面经/B站 AI开发一二面面经.md': 'interview/cpp/bilibili/bilibili-ai-round-1-2',
    'interview/C++/B站面经/哔哩哔哩C++后端开发一面.md': 'interview/cpp/bilibili/bilibili-cpp-backend-round-1',
    'interview/C++/CVTE面经/111.md': 'interview/cpp/cvte/cvte-111',
    'interview/C++/CVTE面经/CVTE一面，纯八股（万字面经）.md': 'interview/cpp/cvte/cvte-round-1-rote',
    'interview/C++/CVTE面经/CVTE校招C++.md': 'interview/cpp/cvte/cvte-campus-cpp',
    'interview/C++/CVTE面经/【秋招面经】CVTE — C++面经，面试体验非常好，但还是不知道为什么没给过。。。.md': 'interview/cpp/cvte/cvte-autumn-cpp',
    'interview/C++/Shopee面经/Shopee秋招C++一二面面经.md': 'interview/cpp/shopee/shopee-autumn-cpp-1-2',
    'interview/C++/Shopee面经/虾皮C++后端一面.md': 'interview/cpp/shopee/shopee-cpp-backend-round-1',
    'interview/C++/Shopee面经/虾皮高性能后端一面.md': 'interview/cpp/shopee/shopee-high-perf-backend-round-1',
    'interview/C++/moment面经/Momenta后端C++实习一二面.md': 'interview/cpp/momenta/momenta-cpp-intern-1-2',
    'interview/C++/moment面经/momenta中间件C++开发一面.md': 'interview/cpp/momenta/momenta-middleware-cpp-round-1',
    'interview/C++/中望面经/中望C++面经，全部内容.md': 'interview/cpp/zwsoft/zwsoft-cpp-full',
    'interview/C++/中望面经/中望软件C++一面.md': 'interview/cpp/zwsoft/zwsoft-cpp-round-1',
    'interview/C++/中望面经/中望软件C++开发面经.md': 'interview/cpp/zwsoft/zwsoft-cpp-dev',
    'interview/C++/其他游戏公司面经/吉比特游戏服务端面经.md': 'interview/cpp/game-companies/gbit-games-server',
    'interview/C++/其他游戏公司面经/游卡C++开发一面面经.md': 'interview/cpp/game-companies/yoka-cpp-round-1',
    'interview/C++/其它/七牛云后端实习面经.md': 'interview/cpp/misc/qiniu-backend-intern',
    'interview/C++/其它/上海期货信息.md': 'interview/cpp/misc/shanghai-futures-info',
    'interview/C++/其它/玄武云（技术面+HR面）.md': 'interview/cpp/misc/xuanwuyun-tech-hr',
    'interview/C++/华为面经/HUAWEI -- C++一面面经.md': 'interview/cpp/huawei/huawei-cpp-round-1',
    'interview/C++/华为面经/HUAWEI -- C++二面面经.md': 'interview/cpp/huawei/huawei-cpp-round-2',
    'interview/C++/华为面经/华为C++二面.md': 'interview/cpp/huawei/huawei-cpp-round-2b',
    'interview/C++/华为面经/华为OD -- C++面经-全.md': 'interview/cpp/huawei/huawei-od-cpp-full',
    'interview/C++/华为面经/华为od--C++面经.md': 'interview/cpp/huawei/huawei-od-cpp',
    'interview/C++/华为面经/华为od-C++面经.md': 'interview/cpp/huawei/huawei-od-cpp-2',
    'interview/C++/华为面经/华为面试高频题目.md': 'interview/cpp/huawei/huawei-interview-topics',
    'interview/C++/同程面经/同程旅行C++.md': 'interview/cpp/tongcheng/tongcheng-cpp',
    'interview/C++/地平线面经/地平线C++一面.md': 'interview/cpp/horizon/horizon-cpp-round-1',
    'interview/C++/声网/声网Linux流媒体C++开发.md': 'interview/cpp/agora/agora-linux-cpp',
    'interview/C++/多益网络面经/多益网络服务器C++开发正式批一面面经.md': 'interview/cpp/duoyi/duoyi-server-cpp-round-1',
    'interview/C++/大疆面经/大疆嵌入式面经.md': 'interview/cpp/dji/dji-embedded',
    'interview/C++/奇安信面经/奇安信C++面经，问的很奇怪。。.md': 'interview/cpp/qianxin/qianxin-cpp',
    'interview/C++/好未来面经/好未来C++客户端面经.md': 'interview/cpp/tal/tal-cpp-client',
    'interview/C++/字节面经/【秋招面经】字节--抖音C++开发面经.md': 'interview/cpp/bytedance/bytedance-douyin-cpp',
    'interview/C++/字节面经/字节C++一面，抖音直播方向.md': 'interview/cpp/bytedance/bytedance-cpp-live-round-1',
    'interview/C++/字节面经/字节C++后端面经.md': 'interview/cpp/bytedance/bytedance-cpp-backend',
    'interview/C++/字节面经/字节C++客户端面经.md': 'interview/cpp/bytedance/bytedance-cpp-client',
    'interview/C++/字节面经/字节C++系统工程师二面.md': 'interview/cpp/bytedance/bytedance-cpp-sys-engineer-2',
    'interview/C++/字节面经/字节剪映C++一面.md': 'interview/cpp/bytedance/bytedance-jianying-cpp-round-1',
    'interview/C++/字节面经/字节推荐架构C++一二面.md': 'interview/cpp/bytedance/bytedance-reco-arch-cpp-1-2',
    'interview/C++/字节面经/字节推荐架构C++一面.md': 'interview/cpp/bytedance/bytedance-reco-arch-cpp-round-1',
    'interview/C++/字节面经/字节豆包C++后端一面，反转链表也太简单了吧。。。.md': 'interview/cpp/bytedance/bytedance-doubao-cpp-round-1',
    'interview/C++/字节面经/字节跳动C++一面.md': 'interview/cpp/bytedance/bytedance-cpp-round-1',
    'interview/C++/字节面经/字节跳动CC++一面面经.md': 'interview/cpp/bytedance/bytedance-ccpp-round-1',
    'interview/C++/字节面经/字节跳动后端开发一面，安全方向.md': 'interview/cpp/bytedance/bytedance-backend-security-round-1',
    'interview/C++/字节面经/字节跳动算法一面.md': 'interview/cpp/bytedance/bytedance-algo-round-1',
    'interview/C++/富途面经/富途 后端c++一面.md': 'interview/cpp/futu/futu-backend-cpp-round-1',
    'interview/C++/小米面经/小米C++一面面经.md': 'interview/cpp/xiaomi/xiaomi-cpp-round-1',
    'interview/C++/小米面经/小米C++二面.md': 'interview/cpp/xiaomi/xiaomi-cpp-round-2',
    'interview/C++/小米面经/小米C++二面面经.md': 'interview/cpp/xiaomi/xiaomi-cpp-round-2b',
    'interview/C++/小米面经/小米C++开发岗一面面经.md': 'interview/cpp/xiaomi/xiaomi-cpp-dev-round-1',
    'interview/C++/小米面经/小米C++开发岗二面面经.md': 'interview/cpp/xiaomi/xiaomi-cpp-dev-round-2',
    'interview/C++/小米面经/小米C++开发，校招一面，纯C++.md': 'interview/cpp/xiaomi/xiaomi-campus-cpp-round-1',
    'interview/C++/小米面经/小米C++开发，校招二面.md': 'interview/cpp/xiaomi/xiaomi-campus-cpp-round-2',
    'interview/C++/小米面经/小米C++软开一二面面经.md': 'interview/cpp/xiaomi/xiaomi-soft-dev-1-2',
    'interview/C++/小米面经/小米C++面经.md': 'interview/cpp/xiaomi/xiaomi-cpp',
    'interview/C++/小米面经/小米安卓一二三面面经，建议收藏！.md': 'interview/cpp/xiaomi/xiaomi-android-1-3',
    'interview/C++/小米面经/小米澎湃OS - C++开发一面.md': 'interview/cpp/xiaomi/xiaomi-hyperos-cpp-round-1',
    'interview/C++/小米面经/小米澎湃OS - C++开发二面.md': 'interview/cpp/xiaomi/xiaomi-hyperos-cpp-round-2',
    'interview/C++/小红书面经/小红书C++引擎架构一面.md': 'interview/cpp/xiaohongshu/xiaohongshu-cpp-engine-round-1',
    'interview/C++/影石面经/影石C++一面面经.md': 'interview/cpp/insta360/insta360-cpp-round-1',
    'interview/C++/影石面经/影石C++二面面经.md': 'interview/cpp/insta360/insta360-cpp-round-2',
    'interview/C++/得物面经/得物一面.md': 'interview/cpp/dewu/dewu-round-1',
    'interview/C++/微博面经/微博一面.md': 'interview/cpp/weibo/weibo-round-1',
    'interview/C++/微博面经/新浪微博C++一二三面面经.md': 'interview/cpp/weibo/weibo-cpp-1-3',
    'interview/C++/快手面经/快手C++一面.md': 'interview/cpp/kuaishou/kuaishou-cpp-round-1',
    'interview/C++/快手面经/快手C++一面，体验感非常nice！！！.md': 'interview/cpp/kuaishou/kuaishou-cpp-round-1-nice',
    'interview/C++/快手面经/快手C++一面，音视频.md': 'interview/cpp/kuaishou/kuaishou-cpp-av-round-1',
    'interview/C++/快手面经/快手C++二面面经.md': 'interview/cpp/kuaishou/kuaishou-cpp-round-2',
    'interview/C++/快手面经/快手C++实习一二面面经，八成是寄了.md': 'interview/cpp/kuaishou/kuaishou-cpp-intern-1-2',
    'interview/C++/快手面经/快手C++开发一面凉经.md': 'interview/cpp/kuaishou/kuaishou-cpp-dev-round-1',
    'interview/C++/快手面经/快手C++面经.md': 'interview/cpp/kuaishou/kuaishou-cpp',
    'interview/C++/快手面经/快手一面，真细节.md': 'interview/cpp/kuaishou/kuaishou-round-1-details',
    'interview/C++/快手面经/快手游戏C++服务端开发一面面经，答了这么多还是寄了.md': 'interview/cpp/kuaishou/kuaishou-games-cpp-round-1',
    'interview/C++/快手面经/快手游戏服务端开发一面，问的真全面啊。。.md': 'interview/cpp/kuaishou/kuaishou-games-server-round-1',
    'interview/C++/快手面经/快手秋招C++二面面经.md': 'interview/cpp/kuaishou/kuaishou-autumn-cpp-round-2',
    'interview/C++/快手面经/快手音视频C++开发.md': 'interview/cpp/kuaishou/kuaishou-av-cpp',
    'interview/C++/快手面经/春招快手后端一面面经.md': 'interview/cpp/kuaishou/kuaishou-spring-backend-round-1',
    'interview/C++/拼多多面经/拼多多 服务端C++开发面经.md': 'interview/cpp/pinduoduo/pdd-server-cpp',
    'interview/C++/拼多多面经/拼多多服务端C++开发一面.md': 'interview/cpp/pinduoduo/pdd-server-cpp-round-1',
    'interview/C++/未岚大陆面经/未岚大陆秋招C++一面.md': 'interview/cpp/weilanda/weilanda-cpp-round-1',
    'interview/C++/海康面经/海康一面过！.md': 'interview/cpp/hikvision/hikvision-round-1-pass',
    'interview/C++/淘米科技面经/淘米科技C++二面.md': 'interview/cpp/taomee/taomee-cpp-round-2',
    'interview/C++/淘米科技面经/淘米科技一面面经.md': 'interview/cpp/taomee/taomee-round-1',
    'interview/C++/深信服面经/深信服C++一面面经.md': 'interview/cpp/sangfor/sangfor-cpp-round-1',
    'interview/C++/滴滴面经/双非本滴滴一面.md': 'interview/cpp/didi/didi-round-1',
    'interview/C++/滴滴面经/滴滴C++一面.md': 'interview/cpp/didi/didi-cpp-round-1',
    'interview/C++/滴滴面经/滴滴C++一面面经.md': 'interview/cpp/didi/didi-cpp-round-1b',
    'interview/C++/滴滴面经/滴滴一面.md': 'interview/cpp/didi/didi-round-1b',
    'interview/C++/理想汽车面经/理想汽车C++一面面经.md': 'interview/cpp/lixiang/lixiang-cpp-round-1',
    'interview/C++/理想汽车面经/理想汽车C++二面面经.md': 'interview/cpp/lixiang/lixiang-cpp-round-2',
    'interview/C++/理想汽车面经/理想汽车C++面经.md': 'interview/cpp/lixiang/lixiang-cpp',
    'interview/C++/理想汽车面经/理想汽车一面面经.md': 'interview/cpp/lixiang/lixiang-round-1',
    'interview/C++/百度面经/25届百度C++实习一面.md': 'interview/cpp/baidu/baidu-cpp-intern-round-1',
    'interview/C++/百度面经/百度C++ 二面凉经.md': 'interview/cpp/baidu/baidu-cpp-round-2',
    'interview/C++/百度面经/百度C++一面.md': 'interview/cpp/baidu/baidu-cpp-round-1',
    'interview/C++/百度面经/百度C++二面面经.md': 'interview/cpp/baidu/baidu-cpp-round-2b',
    'interview/C++/百度面经/百度C++后端研发，all in秋招！.md': 'interview/cpp/baidu/baidu-cpp-backend-all-in',
    'interview/C++/百度面经/百度C++实习一二三面面经.md': 'interview/cpp/baidu/baidu-cpp-intern-1-3',
    'interview/C++/百度面经/百度C++开发一面凉经.md': 'interview/cpp/baidu/baidu-cpp-dev-round-1-cool',
    'interview/C++/百度面经/百度C++开发一面面经.md': 'interview/cpp/baidu/baidu-cpp-dev-round-1',
    'interview/C++/百度面经/百度C++开发二面面经.md': 'interview/cpp/baidu/baidu-cpp-dev-round-2',
    'interview/C++/百度面经/百度IDG秋招C++一面.md': 'interview/cpp/baidu/baidu-idg-cpp-round-1',
    'interview/C++/百度面经/百度内容生态C++一面.md': 'interview/cpp/baidu/baidu-content-cpp-round-1',
    'interview/C++/百度面经/百度地图C++一面.md': 'interview/cpp/baidu/baidu-maps-cpp-round-1',
    'interview/C++/百度面经/百度提前批C++一面.md': 'interview/cpp/baidu/baidu-early-cpp-round-1',
    'interview/C++/百度面经/百度搜索内容技术部c++一面面经.md': 'interview/cpp/baidu/baidu-search-cpp-round-1',
    'interview/C++/百度面经/百度校招C++一面.md': 'interview/cpp/baidu/baidu-campus-cpp-round-1',
    'interview/C++/百度面经/百度秋招C++一二三面面经.md': 'interview/cpp/baidu/baidu-autumn-cpp-1-3',
    'interview/C++/百度面经/百度自动驾驶C++一面，.md': 'interview/cpp/baidu/baidu-selfdriving-cpp-round-1',
    'interview/C++/科大讯飞面经/科大讯飞C++开发一面面经.md': 'interview/cpp/iflytek/iflytek-cpp-round-1',
    'interview/C++/科大讯飞面经/科大讯飞C++面经，建议收藏.md': 'interview/cpp/iflytek/iflytek-cpp',
    'interview/C++/科大讯飞面经/科大讯飞一面面经，暴打C++.md': 'interview/cpp/iflytek/iflytek-round-1',
    'interview/C++/米哈游面经/米哈游C++后端开发一面凉经.md': 'interview/cpp/mihoyo/mihoyo-cpp-round-1-cool',
    'interview/C++/米哈游面经/米哈游一面凉经上.md': 'interview/cpp/mihoyo/mihoyo-round-1-cool-1',
    'interview/C++/米哈游面经/米哈游一面凉经下.md': 'interview/cpp/mihoyo/mihoyo-round-1-cool-2',
    'interview/C++/网易面经/网易互娱.md': 'interview/cpp/netease/netease-games',
    'interview/C++/网易面经/网易雷火服务端开发实习一面.md': 'interview/cpp/netease/netease-leihuo-server-intern-1',
    'interview/C++/美团面经/美团C++客户端一二面面经.md': 'interview/cpp/meituan/meituan-cpp-client-1-2',
    'interview/C++/美团面经/美团中间件C++一面.md': 'interview/cpp/meituan/meituan-middleware-cpp-round-1',
    'interview/C++/美团面经/美团后端C++一面.md': 'interview/cpp/meituan/meituan-backend-cpp-round-1',
    'interview/C++/美团面经/美团后端一二面.md': 'interview/cpp/meituan/meituan-backend-1-2',
    'interview/C++/美团面经/美团后端一面+二面.md': 'interview/cpp/meituan/meituan-backend-1-2-2',
    'interview/C++/美团面经/美团后端一面面经.md': 'interview/cpp/meituan/meituan-backend-round-1',
    'interview/C++/美团面经/美团秋招C++后端一面.md': 'interview/cpp/meituan/meituan-autumn-cpp-round-1',
    'interview/C++/腾讯面经/40亿QQ号，1G内存，怎么去重？——海量数据去重面试题深度解析.md': 'interview/cpp/tencent/qq-dedup-4b-1g',
    'interview/C++/腾讯面经/EG天美工作室后台开发实习一二面凉经.md': 'interview/cpp/tencent/eg-timi-backend-intern-1-2',
    'interview/C++/腾讯面经/真不容易，腾讯给一面了！！！.md': 'interview/cpp/tencent/tencent-round-1-finally',
    'interview/C++/腾讯面经/腾讯C++三面面经.md': 'interview/cpp/tencent/tencent-cpp-round-3',
    'interview/C++/腾讯面经/腾讯C++游戏客户端笔试题.md': 'interview/cpp/tencent/tencent-cpp-game-client-test',
    'interview/C++/腾讯面经/腾讯IEG面经.md': 'interview/cpp/tencent/tencent-ieg',
    'interview/C++/腾讯面经/腾讯PCG+WXG合集.md': 'interview/cpp/tencent/tencent-pcg-wxg',
    'interview/C++/腾讯面经/腾讯PCG一面凉经（后台C++开发岗），.md': 'interview/cpp/tencent/tencent-pcg-round-1-cool',
    'interview/C++/腾讯面经/腾讯QQC++一面.md': 'interview/cpp/tencent/tencent-qq-cpp-round-1',
    'interview/C++/腾讯面经/腾讯QQ浏览器后台开发一面.md': 'interview/cpp/tencent/tencent-qq-browser-backend-1',
    'interview/C++/腾讯面经/腾讯QQ部门C++实习一面.md': 'interview/cpp/tencent/tencent-qq-cpp-intern-1',
    'interview/C++/腾讯面经/腾讯QQ部门C++实习二面.md': 'interview/cpp/tencent/tencent-qq-cpp-intern-2',
    'interview/C++/腾讯面经/腾讯wxg后台开发二面.md': 'interview/cpp/tencent/tencent-wxg-backend-round-2',
    'interview/C++/腾讯面经/腾讯wxg金融微信金融架构部后台开发.md': 'interview/cpp/tencent/tencent-wxg-finance',
    'interview/C++/腾讯面经/腾讯二面.md': 'interview/cpp/tencent/tencent-round-2',
    'interview/C++/腾讯面经/腾讯云后端开发一面.md': 'interview/cpp/tencent/tencent-cloud-backend-round-1',
    'interview/C++/腾讯面经/腾讯云智-后台开发，很基础。。.md': 'interview/cpp/tencent/tencent-yunzhi-backend',
    'interview/C++/腾讯面经/腾讯云智一面面经，洒洒水喽.md': 'interview/cpp/tencent/tencent-yunzhi-round-1',
    'interview/C++/腾讯面经/腾讯会议一面凉经.md': 'interview/cpp/tencent/tencent-meeting-round-1-cool',
    'interview/C++/腾讯面经/腾讯后端暑期实习面经.md': 'interview/cpp/tencent/tencent-backend-summer-intern',
    'interview/C++/腾讯面经/腾讯地图一面.md': 'interview/cpp/tencent/tencent-maps-round-1',
    'interview/C++/腾讯面经/腾讯天美C++后台开发一面面经，只答对了70％，竟然给二面了.md': 'interview/cpp/tencent/tencent-timi-cpp-round-1',
    'interview/C++/腾讯面经/腾讯天美C++面经.md': 'interview/cpp/tencent/tencent-timi-cpp',
    'interview/C++/腾讯面经/腾讯天美一面凉经.md': 'interview/cpp/tencent/tencent-timi-round-1-cool',
    'interview/C++/腾讯面经/腾讯天美游戏C++一面.md': 'interview/cpp/tencent/tencent-timi-game-cpp-round-1',
    'interview/C++/腾讯面经/腾讯微信一面凉经，上来就是两道算法题。。。.md': 'interview/cpp/tencent/tencent-wechat-round-1-cool',
    'interview/C++/腾讯面经/腾讯微信一面挂！.md': 'interview/cpp/tencent/tencent-wechat-round-1-fail',
    'interview/C++/腾讯面经/腾讯微信部门C++开发实习一面.md': 'interview/cpp/tencent/tencent-wechat-cpp-intern-1',
    'interview/C++/腾讯面经/腾讯提前批一面面经.md': 'interview/cpp/tencent/tencent-early-round-1',
    'interview/C++/腾讯面经/腾讯笔试.md': 'interview/cpp/tencent/tencent-written-test',
    'interview/C++/腾讯面经/腾讯音乐后台开发一面，尽力了。。.md': 'interview/cpp/tencent/tencent-music-backend-round-1',
    'interview/C++/虎牙面经/虎牙技术面 C++.md': 'interview/cpp/huya/huya-tech-cpp',
    'interview/C++/迅雷面经/迅雷服务器开发一面面经.md': 'interview/cpp/xunlei/xunlei-server-round-1',
    'interview/C++/金山面经/WPS-C++面经.md': 'interview/cpp/kingsoft/wps-cpp',
    'interview/C++/金山面经/金山C++一面.md': 'interview/cpp/kingsoft/kingsoft-cpp-round-1',
    'interview/C++/金山面经/金山C++一面，强度拉满。。。.md': 'interview/cpp/kingsoft/kingsoft-cpp-round-1-tough',
    'interview/C++/金山面经/金山一面面经，狂虐网络和数据库.md': 'interview/cpp/kingsoft/kingsoft-round-1-net-db',
    'interview/C++/阿里面经/阿里C++研发二面面经.md': 'interview/cpp/alibaba/alibaba-cpp-round-2',
    'interview/C++/阿里面经/阿里一面面经.md': 'interview/cpp/alibaba/alibaba-round-1',
    'interview/C++/阿里面经/阿里云C++二面面经.md': 'interview/cpp/alibaba/alicloud-cpp-round-2',
    'interview/C++/阿里面经/阿里智能信息研发C++.md': 'interview/cpp/alibaba/alibaba-intel-info-cpp',
    'interview/C++/阿里面经/高德C++一面.md': 'interview/cpp/alibaba/amap-cpp-round-1',
    'interview/C++/零跑汽车面经/零跑科技C++一二面面经，.md': 'interview/cpp/leapmotor/leapmotor-cpp-1-2',
    'interview/C++/饿了么面经/饿了么一面凉经，C++选手硬着头皮投了Java岗，奇怪的是还过筛了，然后就被拷打了。。。.md': 'interview/cpp/eleme/eleme-round-1-cool',
    'interview/Go/百度面经/春招百度后端一面面经.md': 'interview/Go/baidu/baidu-backend-round-1-spring',
    'interview/Java/喜马拉雅面经/喜马拉雅Java后端一面.md': 'interview/Java/ximalaya/ximalaya-java-round-1',
    'interview/Java/小红书面经/小红书Java后端一面.md': 'interview/Java/xiaohongshu/xiaohongshu-java-round-1',
    'interview/Java/小鹏汽车面经/小鹏汽车一面面经.md': 'interview/Java/xpeng/xpeng-round-1',
    'interview/Java/快手面经/快手 效率中心 后端实习 一面.md': 'interview/Java/kuaishou/kuaishou-efficiency-intern-1',
    'interview/Java/滴滴面经/滴滴后端一二面，数据库被问麻了。。。.md': 'interview/Java/didi/didi-backend-1-2-db',
    'interview/Java/腾讯面经/校招后端面经系列--腾讯会议一面，面试刚结束，流程就结束了.md': 'interview/Java/tencent/tencent-meeting-campus-round-1',
    'interview/Java/腾讯面经/腾讯 后台开发 一面凉经.md': 'interview/Java/tencent/tencent-backend-round-1-cool',
    'interview/Java/腾讯面经/腾讯音乐Java后端实习一面原题：手撕LRU和接雨水，网友：面完秒挂。。.md': 'interview/Java/tencent/tencent-music-java-lru-rain',
    'interview/Java/诺瓦科技/诺瓦科技一面，认识的都寄了，不知道是不是卡学历。。。.md': 'interview/Java/nova/nova-round-1',
    'linux/Linux常用命令.md': 'linux/linux-common-commands',
    'linux/Shell.md': 'linux/shell',
    'linux/vi快捷键.md': 'linux/vi-shortcuts',
    'network/HTTP、HTTPS详解.md': 'network/http-https-guide',
    'network/TCP、UDP详解.md': 'network/tcp-udp-guide',
    'network/计算机网络总结.md': 'network/computer-network-summary',
    'network/面试官：说说TCP的流量控制和拥塞控制有什么区别？.md': 'network/tcp-flow-vs-congestion',
    'os/深度解析：进程、线程与协程——现代并发编程的核心基石.md': 'os/process-thread-coroutine',
    'os/进程间通信方式.md': 'os/ipc-mechanisms',
    'os/面试连环问-操作系统.md': 'os/os-interview-questions',
    'sql/MySQL/MySQL.md': 'sql/mysql/mysql',
    'sql/MySQL/MySQL查询语句全解.md': 'sql/mysql/mysql-query-guide',
    'sql/Redis/Redis.md': 'sql/redis/redis',
    'sql/Redis/Redis面试连环问.md': 'sql/redis/redis-interview-questions',
    'sql/分布式锁的实现方式深度解析：原理、优缺点与C++实践.md': 'sql/distributed-lock',
}

# 英文路径(无 .md) → 中文标题（侧边栏/首页显示用）
SLUG_TITLES = {'algorithm/huawei-od/count-off-game': '报数游戏', 'algorithm/huawei-od/message-response-time': '报文响应时间', 'algorithm/huawei-od/word-puzzle': '猜字谜', 'algorithm/huawei-od/basketball-game': '篮球游戏', 'algorithm/huawei-od/replant-poplar': '补种未成活胡杨', 'algorithm/nowcoder-top101/binary-search-sort': '二分查找排序', 'algorithm/nowcoder-top101/binary-tree': '二叉树', 'algorithm/nowcoder-top101/dynamic-programming': '动态规划', 'algorithm/nowcoder-top101/two-pointers': '双指针', 'algorithm/nowcoder-top101/hash': '哈希', 'algorithm/nowcoder-top101/stack-queue': '堆栈队列', 'algorithm/nowcoder-top101/string': '字符串', 'algorithm/nowcoder-top101/greedy': '贪心', 'algorithm/nowcoder-top101/recursion-backtracking': '递归回溯', 'algorithm/nowcoder-top101/linked-list': '链表', 'algorithm/interview-100/binary-search/search-insert-position': '面试经典算法题53-搜索插入位置', 'algorithm/interview-100/binary-search/search-2d-matrix': '面试经典算法题54-搜索二维矩阵', 'algorithm/interview-100/binary-search/find-peak-element': '面试经典算法题55-寻找峰值', 'algorithm/interview-100/binary-search/search-rotated-array': '面试经典算法题56-搜索旋转排序数组', 'algorithm/interview-100/binary-search/first-last-position': '面试经典算法题57-在排序数组中查找元素的第一个和最后一个位置', 'algorithm/interview-100/binary-search/median-two-arrays': '面试经典算法题58-寻找两个正序数组的中位数', 'algorithm/interview-100/binary-search/min-rotated-array': '面试经典算法题59-寻找旋转排序数组中的最小值', 'algorithm/interview-100/binary-tree/construct-binary-tree': '面试经典算法题16-从前序与中序遍历序列构造二叉树', 'algorithm/interview-100/binary-tree/symmetric-tree': '面试经典算法题17 - 对称二叉树', 'algorithm/interview-100/binary-tree/level-order-traversal': '面试经典算法题18-二叉树的层序遍历', 'algorithm/interview-100/binary-tree/postorder-traversal': '面试经典算法题19-二叉树的后序遍历', 'algorithm/interview-100/binary-tree/preorder-traversal': '面试经典算法题20-二叉树的前序遍历', 'algorithm/interview-100/binary-tree/right-side-view': '面试经典算法题21-二叉树的右视图', 'algorithm/interview-100/binary-tree/inorder-traversal': '面试经典算法题22-二叉树的中序遍历', 'algorithm/interview-100/binary-tree/max-depth': '面试经典算法题23-二叉树的最大深度', 'algorithm/interview-100/binary-tree/sum-root-to-leaf': '面试经典算法题24-二叉树求根节点到叶子结点数字之和', 'algorithm/interview-100/binary-tree/flatten-binary-tree': '面试经典算法题25-二叉树展开为链表', 'algorithm/interview-100/binary-tree/lowest-common-ancestor': '面试经典算法题26-二叉搜索树的最近公共祖先', 'algorithm/interview-100/binary-tree/mode-bst': '面试经典算法题27-二叉搜索树中的众数', 'algorithm/interview-100/binary-tree/invert-tree': '面试经典算法题28-翻转二叉树', 'algorithm/interview-100/binary-tree/merge-trees': '面试经典算法题29-合并二叉树', 'algorithm/interview-100/binary-tree/path-sum': '面试经典算法题30-路径总和', 'algorithm/interview-100/binary-tree/count-complete-tree-nodes': '面试经典算法题31-完全二叉树的节点个数', 'algorithm/interview-100/binary-tree/validate-bst': '面试经典算法题32-验证二叉树', 'algorithm/interview-100/bit-manipulation/add-binary': '面试经典算法题60-二进制求和', 'algorithm/interview-100/bit-manipulation/reverse-bits': '面试经典算法题61-颠倒二进制位', 'algorithm/interview-100/bit-manipulation/number-of-1-bits': '面试经典算法题62-位1的个数', 'algorithm/interview-100/bit-manipulation/single-number': '面试经典算法题63-只出现一次的数字', 'algorithm/interview-100/bit-manipulation/single-number-2': '面试经典算法题64-只出现一次的数字 II', 'algorithm/interview-100/dynamic-programming/k-steps-ways': '恰好移动 k 步到达某一位置的方法数目', 'algorithm/interview-100/dynamic-programming/climbing-stairs': '面试经典算法题73-爬楼梯', 'algorithm/interview-100/dynamic-programming/house-robber': '面试经典算法题74-打家劫舍', 'algorithm/interview-100/dynamic-programming/word-break': '面试经典算法题75-单词拆分', 'algorithm/interview-100/dynamic-programming/coin-change': '面试经典算法题76-零钱兑换', 'algorithm/interview-100/dynamic-programming/longest-increasing-subseq': '面试经典算法题77-最长递增子序列', 'algorithm/interview-100/dynamic-programming/triangle-min-path': '面试经典算法题78-三角形最小路径和', 'algorithm/interview-100/dynamic-programming/min-path-sum': '面试经典算法题79-最小路径和', 'algorithm/interview-100/dynamic-programming/unique-paths-2': '面试经典算法题80-不同路径 II', 'algorithm/interview-100/dynamic-programming/longest-palindrome': '面试经典算法题81-最长回文子串', 'algorithm/interview-100/dynamic-programming/edit-distance': '面试经典算法题82-编辑距离', 'algorithm/interview-100/dynamic-programming/best-stock-3': '面试经典算法题83-买卖股票的最佳时机 III', 'algorithm/interview-100/dynamic-programming/best-stock-4': '面试经典算法题84-买卖股票的最佳时机 IV', 'algorithm/interview-100/dynamic-programming/max-square': '面试经典算法题85-最大正方形', 'algorithm/interview-100/two-pointers/merge-sorted-arrays': '面试经典算法1-合并两个有序数组', 'algorithm/interview-100/two-pointers/longest-substring': '面试经典算法2-最长无重复子串', 'algorithm/interview-100/two-pointers/is-subsequence': '面试经典算法3-判断子序列', 'algorithm/interview-100/two-pointers/remove-duplicates': '面试经典算法4-删除有序数组中的重复项', 'algorithm/interview-100/two-pointers/container-most-water': '面试经典算法5-盛最多水的容器', 'algorithm/interview-100/two-pointers/3sum': '面试经典算法6-三数之和', 'algorithm/interview-100/hash-table/ransom-note': '面试经典算法题65-赎金信', 'algorithm/interview-100/hash-table/isomorphic-strings': '面试经典算法题66-同构字符串', 'algorithm/interview-100/hash-table/word-pattern': '面试经典算法题67-单词规律', 'algorithm/interview-100/hash-table/valid-anagram': '面试经典算法题68-有效的字母异位词', 'algorithm/interview-100/hash-table/two-sum': '面试经典算法题69-两数之和', 'algorithm/interview-100/hash-table/happy-number': '面试经典算法题70-快乐数', 'algorithm/interview-100/hash-table/contains-duplicate-2': '面试经典算法题71-存在重复元素 II', 'algorithm/interview-100/hash-table/longest-consecutive': '面试经典算法题72-最长连续序列', 'algorithm/interview-100/backtracking/letter-combinations': '面试经典算法题91-电话号码的字母组合', 'algorithm/interview-100/backtracking/combinations': '面试经典算法题92-组合', 'algorithm/interview-100/backtracking/permutations': '面试经典算法题93-全排列', 'algorithm/interview-100/backtracking/combination-sum': '面试经典算法题94-组合总和', 'algorithm/interview-100/backtracking/n-queens-2': '面试经典算法题95-N 皇后 II', 'algorithm/interview-100/backtracking/generate-parentheses': '面试经典算法题96-括号生成', 'algorithm/interview-100/backtracking/word-search': '面试经典算法题97-单词搜索', 'algorithm/interview-100/graph/number-of-islands': '面试经典算法题98-岛屿数量', 'algorithm/interview-100/trie/word-search-2': '面试经典算法题100-单词搜索 II', 'algorithm/interview-100/trie/implement-trie': '面试经典算法题99-实现Tire（前缀树）', 'algorithm/interview-100/array-string/longest-common-prefix': '面试经典算法题33-最长公共前缀', 'algorithm/interview-100/array-string/majority-element': '面试经典算法题34-多数元素', 'algorithm/interview-100/array-string/remove-element': '面试经典算法题35-移除元素', 'algorithm/interview-100/array-string/best-time-stock': '面试经典算法题36-买卖股票的最佳时机', 'algorithm/interview-100/array-string/reverse-words': '面试经典算法题37-反转字符串中的单词', 'algorithm/interview-100/array-string/rotate-array': '面试经典算法题38-轮转数组', 'algorithm/interview-100/array-string/best-time-stock-2': '面试经典算法题39-买卖股票的最佳时机2', 'algorithm/interview-100/array-string/jump-game': '面试经典算法题40-跳跃游戏', 'algorithm/interview-100/array-string/jump-game-2': '面试经典算法题41-跳跃游戏2', 'algorithm/interview-100/array-string/gas-station': '面试经典算法题42-加油站', 'algorithm/interview-100/array-string/zigzag-conversion': '面试经典算法题43-Z字形变换', 'algorithm/interview-100/array-string/trapping-rain-water': '面试经典算法题44-接雨水', 'algorithm/interview-100/array-string/candy': '面试经典算法题45-分发糖果', 'algorithm/interview-100/array-string/first-match-index': '面试经典算法题46-找出字符串中第一个匹配项的下标', 'algorithm/interview-100/stack/valid-parentheses': '面试经典算法题50-有效的括号', 'algorithm/interview-100/stack/min-stack': '面试经典算法题51-最小栈', 'algorithm/interview-100/stack/eval-rpn': '面试经典算法题52-逆波兰表达式求值', 'algorithm/interview-100/sliding-window/min-size-subarray': '面试经典算法题47-长度最小的子数组', 'algorithm/interview-100/sliding-window/substring-concat-words': '面试经典算法题48-串联所有单词的子串', 'algorithm/interview-100/sliding-window/min-window-substring': '面试经典算法题49-最小覆盖子串', 'algorithm/interview-100/matrix/valid-sudoku': '面试经典算法题86-有效的数独', 'algorithm/interview-100/matrix/spiral-matrix': '面试经典算法题87-螺旋矩阵', 'algorithm/interview-100/matrix/rotate-image': '面试经典算法题88-旋转图像', 'algorithm/interview-100/matrix/set-matrix-zeroes': '面试经典算法题89-矩阵置零', 'algorithm/interview-100/matrix/game-of-life': '面试经典算法题90-生命游戏', 'algorithm/interview-100/linked-list/reverse-k-group': '面试经典算法10-K个一组反转链表', 'algorithm/interview-100/linked-list/delete-node': '面试经典算法11-删除链表的节点', 'algorithm/interview-100/linked-list/reorder-list': '面试经典算法12-重排链表', 'algorithm/interview-100/linked-list/remove-nth-from-end': '面试经典算法13-删除链表的倒数第N个结点', 'algorithm/interview-100/linked-list/rotate-list': '面试经典算法14-旋转链表', 'algorithm/interview-100/linked-list/lru-cache': '面试经典算法15-LRU缓存', 'algorithm/interview-100/linked-list/reverse-linked-list': '面试经典算法7-反转链表', 'algorithm/interview-100/linked-list/linked-list-cycle': '面试经典算法8-环形链表', 'algorithm/interview-100/linked-list/reverse-linked-list-2': '面试经典算法9-反转链表Ⅱ', 'cpp/cpp-learning-notes': 'C++学习要点小结', 'cpp/c-basics/c-data-structures-algorithms': 'C语言基础数据结构与算法总结', 'cpp/c-basics/c-reference-guide': 'C语言引用详解', 'cpp/c-basics/c-pointer-guide': 'C语言指针详解', 'cpp/c-basics/c-interview-questions-1': 'C语言高频面试题-1', 'cpp/c-basics/c-interview-questions-2': 'C语言高频面试题-2', 'cpp/cpp-basics/cpp-basics-faq': 'C++ 基础面试问题及详细解答', 'cpp/cpp-basics/cpp11': 'C++11新标准', 'cpp/cpp-basics/cpp14': 'C++14新标准', 'cpp/cpp-basics/cpp17-features': 'C++17新特性', 'cpp/cpp-basics/cpp-stl-analysis': 'C++STL剖析', 'cpp/cpp-basics/cpp-const': 'C++中const关键字的作用', 'cpp/cpp-basics/cpp-new-vs-malloc': 'C++中new和malloc的区别？', 'cpp/cpp-basics/cpp-pointer-vs-reference': 'C++中指针和引用的区别？', 'cpp/cpp-basics/cpp-array-vs-list': 'C++中数组和链表的区别？', 'cpp/cpp-basics/cpp-four-casts': 'C++中的四种cast详解', 'cpp/cpp-basics/cpp-lvalue-rvalue': 'C++中的左值和右值以及一些延伸问题小结', 'cpp/cpp-basics/cpp-overload-override-hide': 'C++中重载、重写、同名隐藏的用法及区别？', 'cpp/cpp-basics/cpp-memory-management': 'C++内存管理深度', 'cpp/cpp-basics/cpp-callable-objects': 'C++可调用对象', 'cpp/cpp-basics/cpp-basic-questions': 'C++基础面试题', 'cpp/cpp-basics/cpp-multithreading': 'C++多线程', 'cpp/cpp-basics/cpp-thread-safety': 'C++多线程线程安全是怎么保证的', 'cpp/cpp-basics/cpp-multithreading-programming': 'C++多线程编程', 'cpp/cpp-basics/cpp-smart-pointers': 'C++智能指针', 'cpp/cpp-basics/cpp-smart-pointers-deep': 'C++智能指针全解析：从auto_ptr到weak_ptr，彻底掌握内存管理利器', 'cpp/cpp-basics/cpp-compilation-process': 'C++的编译过程？', 'cpp/cpp-basics/cpp-virtual-functions': 'C++虚函数', 'cpp/cpp-basics/cpp-design-patterns': 'C++设计模式', 'cpp/cpp-basics/cpp-interview-stl': 'C++面试连环问-STL篇', 'cpp/cpp-basics/cpp-interview-memory': 'C++面试连环问-内存管理篇', 'cpp/cpp-basics/cpp-interview-basics': 'C++面试连环问-基础篇', 'cpp/cpp-basics/cpp-interview-oop': 'C++面试连环问-面向对象篇', 'cpp/cpp-basics/c-cpp-backend-questions': 'C_C++后端开发面试问题与拓展', 'cpp/cpp-basics/tcmalloc-deep-dive': 'TCMalloc深度解析：Google高性能内存分配器的秘密武器', 'cpp/cpp-basics/cpp-static': '一文学透C++中static的用法', 'cpp/cpp-basics/pass-by-value-vs-reference': '值传递、指针传递、引用传递的区别', 'cpp/cpp-basics/hash-collision-solutions': '哈希冲突怎么解决？你学会了吗？', 'cpp/cpp-basics/std-vector-guide': '彻底拿捏stdvector', 'cpp/cpp-basics/spring-interview-cpp-1': '春招C++面经汇总--上', 'cpp/cpp-basics/cpp-shared-ptr-thread-safety': '深入剖析C++ shared_ptr 的线程安全性：从源码到实践', 'cpp/cpp-basics/nowcoder-cpp-algorithms': '牛客网C++社招开发高频算法题目整理', 'cpp/cpp-basics/relearn-cpp': '重学C++', 'data-structure/binary-tree-guide': '二叉树精讲', 'data-structure/ten-sorting-algorithms': '十大排序', 'data-structure/search-algorithms-summary': '常见的查找算法总结', 'data-structure/classic-algorithms-new-grads': '校招生必知必会的几种经典算法', 'data-structure/branch-and-bound': '经典算法-分支限界法', 'data-structure/divide-and-conquer': '经典算法-分治算法', 'data-structure/dynamic-programming': '经典算法-动态规划', 'data-structure/backtracking': '经典算法-回溯算法', 'data-structure/greedy-algorithm': '经典算法-贪心算法', 'git/git-basic-commands': 'Git基本命令', 'git/git-commands-guide': 'Git基本命令详解', 'git/git-in-action': 'Git实战', 'golang/codes/micro-service/final-test-report': 'FINAL_TEST_REPORT', 'golang/codes/micro-service/project-test-report': 'PROJECT_TEST_REPORT', 'golang/codes/micro-service/readme': 'README', 'golang/codes/micro-service/docs/api': 'API', 'golang/files/base/gc-mechanism': 'GC机制', 'golang/files/base/gmp-model': 'GMP模型', 'golang/files/base/gin-framework': 'Gin框架', 'golang/files/base/golang-intro': 'Golang入门', 'golang/files/base/golang-chat-system': 'Golang即时通信系统', 'interview/cpp/qihoo/360-cpp-round-1': '360C++一面面经', 'interview/cpp/qihoo/360-cpp-round-2': '360C++二面面经', 'interview/cpp/qihoo/360-embedded-round-1': '360嵌入式一面', 'interview/cpp/bilibili/bilibili-ai-round-1-2': 'B站 AI开发一二面面经', 'interview/cpp/bilibili/bilibili-cpp-backend-round-1': '哔哩哔哩C++后端开发一面', 'interview/cpp/cvte/cvte-111': '111', 'interview/cpp/cvte/cvte-round-1-rote': 'CVTE一面，纯八股（万字面经）', 'interview/cpp/cvte/cvte-campus-cpp': 'CVTE校招C++', 'interview/cpp/cvte/cvte-autumn-cpp': '【秋招面经】CVTE — C++面经，面试体验非常好，但还是不知道为什么没给过。。。', 'interview/cpp/shopee/shopee-autumn-cpp-1-2': 'Shopee秋招C++一二面面经', 'interview/cpp/shopee/shopee-cpp-backend-round-1': '虾皮C++后端一面', 'interview/cpp/shopee/shopee-high-perf-backend-round-1': '虾皮高性能后端一面', 'interview/cpp/momenta/momenta-cpp-intern-1-2': 'Momenta后端C++实习一二面', 'interview/cpp/momenta/momenta-middleware-cpp-round-1': 'momenta中间件C++开发一面', 'interview/cpp/zwsoft/zwsoft-cpp-full': '中望C++面经，全部内容', 'interview/cpp/zwsoft/zwsoft-cpp-round-1': '中望软件C++一面', 'interview/cpp/zwsoft/zwsoft-cpp-dev': '中望软件C++开发面经', 'interview/cpp/game-companies/gbit-games-server': '吉比特游戏服务端面经', 'interview/cpp/game-companies/yoka-cpp-round-1': '游卡C++开发一面面经', 'interview/cpp/misc/qiniu-backend-intern': '七牛云后端实习面经', 'interview/cpp/misc/shanghai-futures-info': '上海期货信息', 'interview/cpp/misc/xuanwuyun-tech-hr': '玄武云（技术面+HR面）', 'interview/cpp/huawei/huawei-cpp-round-1': 'HUAWEI -- C++一面面经', 'interview/cpp/huawei/huawei-cpp-round-2': 'HUAWEI -- C++二面面经', 'interview/cpp/huawei/huawei-cpp-round-2b': '华为C++二面', 'interview/cpp/huawei/huawei-od-cpp-full': '华为OD -- C++面经-全', 'interview/cpp/huawei/huawei-od-cpp': '华为od--C++面经', 'interview/cpp/huawei/huawei-od-cpp-2': '华为od-C++面经', 'interview/cpp/huawei/huawei-interview-topics': '华为面试高频题目', 'interview/cpp/tongcheng/tongcheng-cpp': '同程旅行C++', 'interview/cpp/horizon/horizon-cpp-round-1': '地平线C++一面', 'interview/cpp/agora/agora-linux-cpp': '声网Linux流媒体C++开发', 'interview/cpp/duoyi/duoyi-server-cpp-round-1': '多益网络服务器C++开发正式批一面面经', 'interview/cpp/dji/dji-embedded': '大疆嵌入式面经', 'interview/cpp/qianxin/qianxin-cpp': '奇安信C++面经，问的很奇怪。。', 'interview/cpp/tal/tal-cpp-client': '好未来C++客户端面经', 'interview/cpp/bytedance/bytedance-douyin-cpp': '【秋招面经】字节--抖音C++开发面经', 'interview/cpp/bytedance/bytedance-cpp-live-round-1': '字节C++一面，抖音直播方向', 'interview/cpp/bytedance/bytedance-cpp-backend': '字节C++后端面经', 'interview/cpp/bytedance/bytedance-cpp-client': '字节C++客户端面经', 'interview/cpp/bytedance/bytedance-cpp-sys-engineer-2': '字节C++系统工程师二面', 'interview/cpp/bytedance/bytedance-jianying-cpp-round-1': '字节剪映C++一面', 'interview/cpp/bytedance/bytedance-reco-arch-cpp-1-2': '字节推荐架构C++一二面', 'interview/cpp/bytedance/bytedance-reco-arch-cpp-round-1': '字节推荐架构C++一面', 'interview/cpp/bytedance/bytedance-doubao-cpp-round-1': '字节豆包C++后端一面，反转链表也太简单了吧。。。', 'interview/cpp/bytedance/bytedance-cpp-round-1': '字节跳动C++一面', 'interview/cpp/bytedance/bytedance-ccpp-round-1': '字节跳动CC++一面面经', 'interview/cpp/bytedance/bytedance-backend-security-round-1': '字节跳动后端开发一面，安全方向', 'interview/cpp/bytedance/bytedance-algo-round-1': '字节跳动算法一面', 'interview/cpp/futu/futu-backend-cpp-round-1': '富途 后端c++一面', 'interview/cpp/xiaomi/xiaomi-cpp-round-1': '小米C++一面面经', 'interview/cpp/xiaomi/xiaomi-cpp-round-2': '小米C++二面', 'interview/cpp/xiaomi/xiaomi-cpp-round-2b': '小米C++二面面经', 'interview/cpp/xiaomi/xiaomi-cpp-dev-round-1': '小米C++开发岗一面面经', 'interview/cpp/xiaomi/xiaomi-cpp-dev-round-2': '小米C++开发岗二面面经', 'interview/cpp/xiaomi/xiaomi-campus-cpp-round-1': '小米C++开发，校招一面，纯C++', 'interview/cpp/xiaomi/xiaomi-campus-cpp-round-2': '小米C++开发，校招二面', 'interview/cpp/xiaomi/xiaomi-soft-dev-1-2': '小米C++软开一二面面经', 'interview/cpp/xiaomi/xiaomi-cpp': '小米C++面经', 'interview/cpp/xiaomi/xiaomi-android-1-3': '小米安卓一二三面面经，建议收藏！', 'interview/cpp/xiaomi/xiaomi-hyperos-cpp-round-1': '小米澎湃OS - C++开发一面', 'interview/cpp/xiaomi/xiaomi-hyperos-cpp-round-2': '小米澎湃OS - C++开发二面', 'interview/cpp/xiaohongshu/xiaohongshu-cpp-engine-round-1': '小红书C++引擎架构一面', 'interview/cpp/insta360/insta360-cpp-round-1': '影石C++一面面经', 'interview/cpp/insta360/insta360-cpp-round-2': '影石C++二面面经', 'interview/cpp/dewu/dewu-round-1': '得物一面', 'interview/cpp/weibo/weibo-round-1': '微博一面', 'interview/cpp/weibo/weibo-cpp-1-3': '新浪微博C++一二三面面经', 'interview/cpp/kuaishou/kuaishou-cpp-round-1': '快手C++一面', 'interview/cpp/kuaishou/kuaishou-cpp-round-1-nice': '快手C++一面，体验感非常nice！！！', 'interview/cpp/kuaishou/kuaishou-cpp-av-round-1': '快手C++一面，音视频', 'interview/cpp/kuaishou/kuaishou-cpp-round-2': '快手C++二面面经', 'interview/cpp/kuaishou/kuaishou-cpp-intern-1-2': '快手C++实习一二面面经，八成是寄了', 'interview/cpp/kuaishou/kuaishou-cpp-dev-round-1': '快手C++开发一面凉经', 'interview/cpp/kuaishou/kuaishou-cpp': '快手C++面经', 'interview/cpp/kuaishou/kuaishou-round-1-details': '快手一面，真细节', 'interview/cpp/kuaishou/kuaishou-games-cpp-round-1': '快手游戏C++服务端开发一面面经，答了这么多还是寄了', 'interview/cpp/kuaishou/kuaishou-games-server-round-1': '快手游戏服务端开发一面，问的真全面啊。。', 'interview/cpp/kuaishou/kuaishou-autumn-cpp-round-2': '快手秋招C++二面面经', 'interview/cpp/kuaishou/kuaishou-av-cpp': '快手音视频C++开发', 'interview/cpp/kuaishou/kuaishou-spring-backend-round-1': '春招快手后端一面面经', 'interview/cpp/pinduoduo/pdd-server-cpp': '拼多多 服务端C++开发面经', 'interview/cpp/pinduoduo/pdd-server-cpp-round-1': '拼多多服务端C++开发一面', 'interview/cpp/weilanda/weilanda-cpp-round-1': '未岚大陆秋招C++一面', 'interview/cpp/hikvision/hikvision-round-1-pass': '海康一面过！', 'interview/cpp/taomee/taomee-cpp-round-2': '淘米科技C++二面', 'interview/cpp/taomee/taomee-round-1': '淘米科技一面面经', 'interview/cpp/sangfor/sangfor-cpp-round-1': '深信服C++一面面经', 'interview/cpp/didi/didi-round-1': '双非本滴滴一面', 'interview/cpp/didi/didi-cpp-round-1': '滴滴C++一面', 'interview/cpp/didi/didi-cpp-round-1b': '滴滴C++一面面经', 'interview/cpp/didi/didi-round-1b': '滴滴一面', 'interview/cpp/lixiang/lixiang-cpp-round-1': '理想汽车C++一面面经', 'interview/cpp/lixiang/lixiang-cpp-round-2': '理想汽车C++二面面经', 'interview/cpp/lixiang/lixiang-cpp': '理想汽车C++面经', 'interview/cpp/lixiang/lixiang-round-1': '理想汽车一面面经', 'interview/cpp/baidu/baidu-cpp-intern-round-1': '25届百度C++实习一面', 'interview/cpp/baidu/baidu-cpp-round-2': '百度C++ 二面凉经', 'interview/cpp/baidu/baidu-cpp-round-1': '百度C++一面', 'interview/cpp/baidu/baidu-cpp-round-2b': '百度C++二面面经', 'interview/cpp/baidu/baidu-cpp-backend-all-in': '百度C++后端研发，all in秋招！', 'interview/cpp/baidu/baidu-cpp-intern-1-3': '百度C++实习一二三面面经', 'interview/cpp/baidu/baidu-cpp-dev-round-1-cool': '百度C++开发一面凉经', 'interview/cpp/baidu/baidu-cpp-dev-round-1': '百度C++开发一面面经', 'interview/cpp/baidu/baidu-cpp-dev-round-2': '百度C++开发二面面经', 'interview/cpp/baidu/baidu-idg-cpp-round-1': '百度IDG秋招C++一面', 'interview/cpp/baidu/baidu-content-cpp-round-1': '百度内容生态C++一面', 'interview/cpp/baidu/baidu-maps-cpp-round-1': '百度地图C++一面', 'interview/cpp/baidu/baidu-early-cpp-round-1': '百度提前批C++一面', 'interview/cpp/baidu/baidu-search-cpp-round-1': '百度搜索内容技术部c++一面面经', 'interview/cpp/baidu/baidu-campus-cpp-round-1': '百度校招C++一面', 'interview/cpp/baidu/baidu-autumn-cpp-1-3': '百度秋招C++一二三面面经', 'interview/cpp/baidu/baidu-selfdriving-cpp-round-1': '百度自动驾驶C++一面，', 'interview/cpp/iflytek/iflytek-cpp-round-1': '科大讯飞C++开发一面面经', 'interview/cpp/iflytek/iflytek-cpp': '科大讯飞C++面经，建议收藏', 'interview/cpp/iflytek/iflytek-round-1': '科大讯飞一面面经，暴打C++', 'interview/cpp/mihoyo/mihoyo-cpp-round-1-cool': '米哈游C++后端开发一面凉经', 'interview/cpp/mihoyo/mihoyo-round-1-cool-1': '米哈游一面凉经上', 'interview/cpp/mihoyo/mihoyo-round-1-cool-2': '米哈游一面凉经下', 'interview/cpp/netease/netease-games': '网易互娱', 'interview/cpp/netease/netease-leihuo-server-intern-1': '网易雷火服务端开发实习一面', 'interview/cpp/meituan/meituan-cpp-client-1-2': '美团C++客户端一二面面经', 'interview/cpp/meituan/meituan-middleware-cpp-round-1': '美团中间件C++一面', 'interview/cpp/meituan/meituan-backend-cpp-round-1': '美团后端C++一面', 'interview/cpp/meituan/meituan-backend-1-2': '美团后端一二面', 'interview/cpp/meituan/meituan-backend-1-2-2': '美团后端一面+二面', 'interview/cpp/meituan/meituan-backend-round-1': '美团后端一面面经', 'interview/cpp/meituan/meituan-autumn-cpp-round-1': '美团秋招C++后端一面', 'interview/cpp/tencent/qq-dedup-4b-1g': '40亿QQ号，1G内存，怎么去重？——海量数据去重面试题深度解析', 'interview/cpp/tencent/eg-timi-backend-intern-1-2': 'EG天美工作室后台开发实习一二面凉经', 'interview/cpp/tencent/tencent-round-1-finally': '真不容易，腾讯给一面了！！！', 'interview/cpp/tencent/tencent-cpp-round-3': '腾讯C++三面面经', 'interview/cpp/tencent/tencent-cpp-game-client-test': '腾讯C++游戏客户端笔试题', 'interview/cpp/tencent/tencent-ieg': '腾讯IEG面经', 'interview/cpp/tencent/tencent-pcg-wxg': '腾讯PCG+WXG合集', 'interview/cpp/tencent/tencent-pcg-round-1-cool': '腾讯PCG一面凉经（后台C++开发岗），', 'interview/cpp/tencent/tencent-qq-cpp-round-1': '腾讯QQC++一面', 'interview/cpp/tencent/tencent-qq-browser-backend-1': '腾讯QQ浏览器后台开发一面', 'interview/cpp/tencent/tencent-qq-cpp-intern-1': '腾讯QQ部门C++实习一面', 'interview/cpp/tencent/tencent-qq-cpp-intern-2': '腾讯QQ部门C++实习二面', 'interview/cpp/tencent/tencent-wxg-backend-round-2': '腾讯wxg后台开发二面', 'interview/cpp/tencent/tencent-wxg-finance': '腾讯wxg金融微信金融架构部后台开发', 'interview/cpp/tencent/tencent-round-2': '腾讯二面', 'interview/cpp/tencent/tencent-cloud-backend-round-1': '腾讯云后端开发一面', 'interview/cpp/tencent/tencent-yunzhi-backend': '腾讯云智-后台开发，很基础。。', 'interview/cpp/tencent/tencent-yunzhi-round-1': '腾讯云智一面面经，洒洒水喽', 'interview/cpp/tencent/tencent-meeting-round-1-cool': '腾讯会议一面凉经', 'interview/cpp/tencent/tencent-backend-summer-intern': '腾讯后端暑期实习面经', 'interview/cpp/tencent/tencent-maps-round-1': '腾讯地图一面', 'interview/cpp/tencent/tencent-timi-cpp-round-1': '腾讯天美C++后台开发一面面经，只答对了70％，竟然给二面了', 'interview/cpp/tencent/tencent-timi-cpp': '腾讯天美C++面经', 'interview/cpp/tencent/tencent-timi-round-1-cool': '腾讯天美一面凉经', 'interview/cpp/tencent/tencent-timi-game-cpp-round-1': '腾讯天美游戏C++一面', 'interview/cpp/tencent/tencent-wechat-round-1-cool': '腾讯微信一面凉经，上来就是两道算法题。。。', 'interview/cpp/tencent/tencent-wechat-round-1-fail': '腾讯微信一面挂！', 'interview/cpp/tencent/tencent-wechat-cpp-intern-1': '腾讯微信部门C++开发实习一面', 'interview/cpp/tencent/tencent-early-round-1': '腾讯提前批一面面经', 'interview/cpp/tencent/tencent-written-test': '腾讯笔试', 'interview/cpp/tencent/tencent-music-backend-round-1': '腾讯音乐后台开发一面，尽力了。。', 'interview/cpp/huya/huya-tech-cpp': '虎牙技术面 C++', 'interview/cpp/xunlei/xunlei-server-round-1': '迅雷服务器开发一面面经', 'interview/cpp/kingsoft/wps-cpp': 'WPS-C++面经', 'interview/cpp/kingsoft/kingsoft-cpp-round-1': '金山C++一面', 'interview/cpp/kingsoft/kingsoft-cpp-round-1-tough': '金山C++一面，强度拉满。。。', 'interview/cpp/kingsoft/kingsoft-round-1-net-db': '金山一面面经，狂虐网络和数据库', 'interview/cpp/alibaba/alibaba-cpp-round-2': '阿里C++研发二面面经', 'interview/cpp/alibaba/alibaba-round-1': '阿里一面面经', 'interview/cpp/alibaba/alicloud-cpp-round-2': '阿里云C++二面面经', 'interview/cpp/alibaba/alibaba-intel-info-cpp': '阿里智能信息研发C++', 'interview/cpp/alibaba/amap-cpp-round-1': '高德C++一面', 'interview/cpp/leapmotor/leapmotor-cpp-1-2': '零跑科技C++一二面面经，', 'interview/cpp/eleme/eleme-round-1-cool': '饿了么一面凉经，C++选手硬着头皮投了Java岗，奇怪的是还过筛了，然后就被拷打了。。。', 'interview/Go/baidu/baidu-backend-round-1-spring': '春招百度后端一面面经', 'interview/Java/ximalaya/ximalaya-java-round-1': '喜马拉雅Java后端一面', 'interview/Java/xiaohongshu/xiaohongshu-java-round-1': '小红书Java后端一面', 'interview/Java/xpeng/xpeng-round-1': '小鹏汽车一面面经', 'interview/Java/kuaishou/kuaishou-efficiency-intern-1': '快手 效率中心 后端实习 一面', 'interview/Java/didi/didi-backend-1-2-db': '滴滴后端一二面，数据库被问麻了。。。', 'interview/Java/tencent/tencent-meeting-campus-round-1': '校招后端面经系列--腾讯会议一面，面试刚结束，流程就结束了', 'interview/Java/tencent/tencent-backend-round-1-cool': '腾讯 后台开发 一面凉经', 'interview/Java/tencent/tencent-music-java-lru-rain': '腾讯音乐Java后端实习一面原题：手撕LRU和接雨水，网友：面完秒挂。。', 'interview/Java/nova/nova-round-1': '诺瓦科技一面，认识的都寄了，不知道是不是卡学历。。。', 'linux/linux-common-commands': 'Linux常用命令', 'linux/shell': 'Shell', 'linux/vi-shortcuts': 'vi快捷键', 'network/http-https-guide': 'HTTP、HTTPS详解', 'network/tcp-udp-guide': 'TCP、UDP详解', 'network/computer-network-summary': '计算机网络总结', 'network/tcp-flow-vs-congestion': '面试官：说说TCP的流量控制和拥塞控制有什么区别？', 'os/process-thread-coroutine': '深度解析：进程、线程与协程——现代并发编程的核心基石', 'os/ipc-mechanisms': '进程间通信方式', 'os/os-interview-questions': '面试连环问-操作系统', 'sql/mysql/mysql': 'MySQL', 'sql/mysql/mysql-query-guide': 'MySQL查询语句全解', 'sql/redis/redis': 'Redis', 'sql/redis/redis-interview-questions': 'Redis面试连环问', 'sql/distributed-lock': '分布式锁的实现方式深度解析：原理、优缺点与C++实践'}

